baseurl = "/" # Hostname (and path) to the root.
title = "E1ixir" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The siteâ€™s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Evi1haxor" # Author's name.
    info = "A Subtle Machinery of awe..." # Author's job title or info.
    description = "A Sorry Little affair. Blame: Archit Dwivedi." # Site description.
    keywords = "blog,developer,personal" # Site keywords.

    disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/evi1haxor/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/evi1haxor/"
[[params.social]]
    name = "Telegram"
    weight = 3
    url = "https://t.me/evi1haxor/"
[[params.social]]
    name = "E1ixir"
    weight = 3
    url = "https://t.me/E1ixir/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Timeline"
    weight = 3
    url  = "/timeline/"
